"""Add scholarship_type_id to email_templates + replace single-key unique with compound.

Closes the schema half of issue #647 — per-scholarship email templates were
the missing piece blocking 5 of the 6 ``/admin/scholarship-email-templates/*``
endpoints from working.

# Schema changes

1. Add column ``scholarship_type_id INTEGER NULL`` with FK to ``scholarship_types.id``.
   NULL means "generic template" (applies to all scholarships).
2. Drop the existing single-column unique constraint on ``key``. Defensive:
   the constraint name is auto-generated by alembic from the model's
   ``Column(... unique=True)``, so we look it up by column rather than
   hard-coding the name.
3. Add compound unique on ``(key, scholarship_type_id)``. Postgres allows
   multiple NULLs in a unique constraint by default, so generic templates
   and per-scholarship overrides for the same key coexist.

# Safety

- ``op.add_column`` is non-destructive; existing rows get NULL = generic.
- The constraint swap is the only mutating change. If the lookup of the
  old constraint name fails (e.g., on a fresh DB where the unique was
  created via the new schema), the migration falls back gracefully.

Revision ID: email_tpl_scholarship_type_id_001
Revises: merge_20260515_heads
Create Date: 2026-05-15
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "email_tpl_scholarship_type_id_001"
down_revision: Union[str, Sequence[str], None] = "merge_20260515_heads"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _existing_key_unique_constraint_name(inspector) -> Union[str, None]:
    """Return the auto-generated name of the existing single-column unique on ``key``.

    The constraint may have been created either as a real UNIQUE CONSTRAINT
    or as a UNIQUE INDEX; check both. Returns ``None`` if neither is found
    (e.g., a fresh DB built directly from the new model).
    """
    for c in inspector.get_unique_constraints("email_templates"):
        if c.get("column_names") == ["key"]:
            return c["name"]
    for ix in inspector.get_indexes("email_templates"):
        if ix.get("unique") and ix.get("column_names") == ["key"]:
            return ix["name"]
    return None


def _fk_on_email_automation_rules_template_key(inspector) -> Union[str, None]:
    """Return the auto-generated FK name on ``email_automation_rules.template_key``
    pointing at ``email_templates.key``.

    This FK was added in migration ``c5d8f9a2b3e1`` and now blocks dropping the
    single-column unique on ``email_templates.key`` (PostgreSQL requires the
    referenced columns to have a unique constraint). The application layer
    handles override-vs-generic template lookup, so dropping this DB-level FK
    is safe.
    """
    if "email_automation_rules" not in inspector.get_table_names():
        return None
    for fk in inspector.get_foreign_keys("email_automation_rules"):
        if fk.get("referred_table") == "email_templates" and fk.get("referred_columns") == ["key"]:
            return fk.get("name")
    return None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    existing_columns = {c["name"] for c in inspector.get_columns("email_templates")}

    # 1. Drop the FK from email_automation_rules.template_key → email_templates.key.
    #    Otherwise step 3's drop of the single-column unique fails with
    #    "no unique constraint matching given keys for referenced table".
    fk_name = _fk_on_email_automation_rules_template_key(inspector)
    if fk_name:
        op.drop_constraint(fk_name, "email_automation_rules", type_="foreignkey")

    # 2. Add scholarship_type_id column + FK + supporting index.
    if "scholarship_type_id" not in existing_columns:
        op.add_column(
            "email_templates",
            sa.Column("scholarship_type_id", sa.Integer(), nullable=True),
        )
        op.create_foreign_key(
            "fk_email_templates_scholarship_type",
            "email_templates",
            "scholarship_types",
            ["scholarship_type_id"],
            ["id"],
        )
        op.create_index(
            "ix_email_templates_scholarship_type_id",
            "email_templates",
            ["scholarship_type_id"],
        )

    # 3. Drop the auto-generated single-column unique on ``key``.
    existing_unique_name = _existing_key_unique_constraint_name(inspector)
    if existing_unique_name:
        # Try dropping as a unique constraint first; fall back to index drop.
        try:
            op.drop_constraint(existing_unique_name, "email_templates", type_="unique")
        except Exception:
            op.drop_index(existing_unique_name, table_name="email_templates")

    # 4. Add the compound unique constraint.
    existing_constraint_names = {c["name"] for c in inspector.get_unique_constraints("email_templates")}
    if "uq_email_templates_key_scholarship" not in existing_constraint_names:
        op.create_unique_constraint(
            "uq_email_templates_key_scholarship",
            "email_templates",
            ["key", "scholarship_type_id"],
        )


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    existing_constraint_names = {c["name"] for c in inspector.get_unique_constraints("email_templates")}
    if "uq_email_templates_key_scholarship" in existing_constraint_names:
        op.drop_constraint("uq_email_templates_key_scholarship", "email_templates", type_="unique")

    # Restore the auto-generated single-column unique on ``key`` (matches
    # the pre-upgrade Column(..., unique=True) form).
    op.create_unique_constraint("email_templates_key_key", "email_templates", ["key"])

    existing_indexes = {ix["name"] for ix in inspector.get_indexes("email_templates")}
    if "ix_email_templates_scholarship_type_id" in existing_indexes:
        op.drop_index("ix_email_templates_scholarship_type_id", table_name="email_templates")

    # Best-effort FK drop — name was set explicitly above so this is stable.
    try:
        op.drop_constraint("fk_email_templates_scholarship_type", "email_templates", type_="foreignkey")
    except Exception:
        pass

    existing_columns = {c["name"] for c in inspector.get_columns("email_templates")}
    if "scholarship_type_id" in existing_columns:
        op.drop_column("email_templates", "scholarship_type_id")

    # Restore the FK on email_automation_rules.template_key → email_templates.key
    # so post-downgrade schema matches the pre-upgrade state.
    if "email_automation_rules" in inspector.get_table_names():
        op.create_foreign_key(
            "fk_email_automation_rules_template_key",
            "email_automation_rules",
            "email_templates",
            ["template_key"],
            ["key"],
        )
