"""add_scholarship_email_templates_table

Revision ID: 5ac85532364d
Revises: d4198ecb46e2
Create Date: 2025-09-18 07:03:09.104028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5ac85532364d'
down_revision: Union[str, None] = 'd4198ecb46e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarship_email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scholarship_type_id', sa.Integer(), nullable=False),
    sa.Column('email_template_key', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('custom_subject', sa.String(length=255), nullable=True),
    sa.Column('custom_body', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['email_template_key'], ['email_templates.key'], ),
    sa.ForeignKeyConstraint(['scholarship_type_id'], ['scholarship_types.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scholarship_type_id', 'email_template_key', name='uq_scholarship_email_template')
    )
    op.create_index(op.f('ix_scholarship_email_templates_id'), 'scholarship_email_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scholarship_email_templates_id'), table_name='scholarship_email_templates')
    op.drop_table('scholarship_email_templates')
    # ### end Alembic commands ###