"""initial_schema_without_student_table

Revision ID: ea5d2bc75b8b
Revises: 
Create Date: 2025-01-08 12:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea5d2bc75b8b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Helper function to check if table exists
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    def table_exists(table_name):
        return table_name in existing_tables

    # Create degrees table if it doesn't exist
    if not table_exists("degrees"):
        op.create_table(
            "degrees",
            sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
            sa.Column("code", sa.String(10), nullable=False),
            sa.Column("name", sa.String(100), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("code", name="uq_degree_code_unique"),
        )

    # Create enroll_types table if it doesn't exist
    if not table_exists("enroll_types"):
        op.create_table(
            "enroll_types",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("degreeId", sa.SmallInteger(), nullable=False),
            sa.Column("code", sa.String(10), nullable=False),
            sa.Column("name", sa.String(100), nullable=False),
            sa.ForeignKeyConstraint(["degreeId"], ["degrees.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_unique_constraint(
            "uq_degree_code", "enroll_types", ["degreeId", "code"]
        )

    # Create identities table if it doesn't exist
    if not table_exists("identities"):
        op.create_table(
            "identities",
            sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
            sa.Column("code", sa.String(10), nullable=False),
            sa.Column("name", sa.String(100), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("code"),
        )

    # Create school_identities table if it doesn't exist
    if not table_exists("school_identities"):
        op.create_table(
            "school_identities",
            sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
            sa.Column("code", sa.String(10), nullable=False),
            sa.Column("name", sa.String(100), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("code"),
        )

    # Create studying_statuses table if it doesn't exist
    if not table_exists("studying_statuses"):
        op.create_table(
            "studying_statuses",
            sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
            sa.Column("code", sa.String(10), nullable=False),
            sa.Column("name", sa.String(100), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("code"),
        )

    # Create users table (basic structure needed for foreign keys)
    if not table_exists("users"):
        op.create_table(
            "users",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("email", sa.String(255), nullable=False),
            sa.Column("hashed_password", sa.String(255), nullable=True),
            sa.Column("is_active", sa.Boolean(), default=True, nullable=False),
            sa.Column("is_superuser", sa.Boolean(), default=False, nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("email"),
        )

    # Create enums for notifications using raw SQL to handle existence properly
    op.execute(
        """
        DO $$ BEGIN
            CREATE TYPE notificationtype AS ENUM ('INFO', 'WARNING', 'ERROR', 'SUCCESS', 'REMINDER');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """
    )

    op.execute(
        """
        DO $$ BEGIN
            CREATE TYPE notificationpriority AS ENUM ('LOW', 'NORMAL', 'HIGH', 'URGENT');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """
    )

    # Create notifications table using raw SQL to avoid enum creation issues
    if not table_exists("notifications"):
        op.execute(
            """
            CREATE TABLE notifications (
                id SERIAL PRIMARY KEY,
                user_id INTEGER REFERENCES users(id),
                title VARCHAR(255) NOT NULL,
                message TEXT NOT NULL,
                notification_type notificationtype NOT NULL,
                priority notificationpriority NOT NULL,
                is_read BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
        """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notifications")
    op.execute("DROP TYPE IF EXISTS notificationtype CASCADE")
    op.execute("DROP TYPE IF EXISTS notificationpriority CASCADE")
    op.drop_table("users")
    op.drop_table("studying_statuses")
    op.drop_table("school_identities")
    op.drop_table("identities")
    op.drop_constraint("uq_degree_code", "enroll_types", type_="unique")
    op.drop_table("enroll_types")
    op.drop_table("degrees")
    # ### end Alembic commands ###
