"""initial_schema_without_student_table

Revision ID: ea5d2bc75b8b
Revises: 
Create Date: 2025-08-05 07:00:30.693343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea5d2bc75b8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create degrees table if it doesn't exist
    op.create_table('degrees',
        sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column('code', sa.String(10), nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code', name='uq_degree_code_unique')
    )
    
    # Create enroll_types table if it doesn't exist
    op.create_table('enroll_types',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('degreeId', sa.SmallInteger(), nullable=False),
        sa.Column('code', sa.String(10), nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.ForeignKeyConstraint(['degreeId'], ['degrees.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('uq_degree_code', 'enroll_types', ['degreeId', 'code'])
    
    # Create identities table if it doesn't exist
    op.create_table('identities',
        sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column('code', sa.String(10), nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    
    # Create school_identities table if it doesn't exist  
    op.create_table('school_identities',
        sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column('code', sa.String(10), nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    
    # Create studying_statuses table if it doesn't exist
    op.create_table('studying_statuses',
        sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column('code', sa.String(10), nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studying_statuses')
    op.drop_table('school_identities') 
    op.drop_table('identities')
    op.drop_constraint('uq_degree_code', 'enroll_types', type_='unique')
    op.drop_table('enroll_types')
    op.drop_table('degrees')
    # ### end Alembic commands ###