"""initial_schema_without_student_table

Revision ID: ea5d2bc75b8b
Revises: 
Create Date: 2025-08-05 07:00:30.693343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea5d2bc75b8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create degrees table if it doesn't exist
    op.create_table('degrees',
        sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column('code', sa.String(10), nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code', name='uq_degree_code_unique')
    )
    
    # Create enroll_types table if it doesn't exist
    op.create_table('enroll_types',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('degreeId', sa.SmallInteger(), nullable=False),
        sa.Column('code', sa.String(10), nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.ForeignKeyConstraint(['degreeId'], ['degrees.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('uq_degree_code', 'enroll_types', ['degreeId', 'code'])
    
    # Create identities table if it doesn't exist
    op.create_table('identities',
        sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column('code', sa.String(10), nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    
    # Create school_identities table if it doesn't exist  
    op.create_table('school_identities',
        sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column('code', sa.String(10), nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    
    # Create studying_statuses table if it doesn't exist
    op.create_table('studying_statuses',
        sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column('code', sa.String(10), nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    
    # Create users table (basic structure needed for foreign keys)
    op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(255), nullable=False),
        sa.Column('username', sa.String(100), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    
    # Create enums for notifications
    notification_type_enum = sa.Enum(
        'INFO', 'WARNING', 'ERROR', 'SUCCESS', 'REMINDER',
        name='notificationtype'
    )
    notification_priority_enum = sa.Enum(
        'LOW', 'NORMAL', 'HIGH', 'URGENT',
        name='notificationpriority'  
    )
    
    notification_type_enum.create(op.get_bind())
    notification_priority_enum.create(op.get_bind())
    
    # Create notifications table
    op.create_table('notifications',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(255), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('notification_type', notification_type_enum, nullable=False),
        sa.Column('priority', notification_priority_enum, nullable=False),
        sa.Column('is_read', sa.Boolean(), default=False, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.execute('DROP TYPE IF EXISTS notificationtype CASCADE')
    op.execute('DROP TYPE IF EXISTS notificationpriority CASCADE')
    op.drop_table('users')
    op.drop_table('studying_statuses')
    op.drop_table('school_identities') 
    op.drop_table('identities')
    op.drop_constraint('uq_degree_code', 'enroll_types', type_='unique')
    op.drop_table('enroll_types')
    op.drop_table('degrees')
    # ### end Alembic commands ###