# Example Production Deployment Workflow
# Copy this file to your production repository at: .github/workflows/deploy.yml

name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - production
          - staging
        default: 'production'

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (or your registry)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            your-org/scholarship-backend:latest
            your-org/scholarship-backend:${{ github.sha }}
          cache-from: type=registry,ref=your-org/scholarship-backend:buildcache
          cache-to: type=registry,ref=your-org/scholarship-backend:buildcache,mode=max

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            your-org/scholarship-frontend:latest
            your-org/scholarship-frontend:${{ github.sha }}
          cache-from: type=registry,ref=your-org/scholarship-frontend:buildcache
          cache-to: type=registry,ref=your-org/scholarship-frontend:buildcache,mode=max

      - name: Deploy to production server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
          SERVER_HOST: ${{ secrets.PRODUCTION_SERVER }}
          SERVER_USER: ${{ secrets.PRODUCTION_USER }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts

          # Deploy via SSH
          ssh -i ~/.ssh/deploy_key "$SERVER_USER@$SERVER_HOST" << 'ENDSSH'
            cd /opt/scholarship-system

            # Pull latest images
            docker compose pull

            # Backup database
            docker compose exec -T postgres pg_dump -U scholarship_user scholarship_db > backup-$(date +%Y%m%d-%H%M%S).sql

            # Restart services with zero downtime
            docker compose up -d --remove-orphans

            # Wait for health checks
            sleep 10

            # Verify services are healthy
            docker compose ps
          ENDSSH

          echo "âœ… Deployment completed successfully"

      - name: Run smoke tests
        run: |
          # Wait for application to be ready
          sleep 30

          # Test API health
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://api.production.example.com/health)
          if [ "$RESPONSE" != "200" ]; then
            echo "::error::API health check failed"
            exit 1
          fi

          # Test frontend
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://production.example.com)
          if [ "$RESPONSE" != "200" ]; then
            echo "::error::Frontend health check failed"
            exit 1
          fi

          echo "âœ… Smoke tests passed"

      - name: Notify on success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const message = `
            ðŸš€ **Deployment Successful**

            - Environment: ${{ github.event.inputs.environment || 'production' }}
            - Commit: ${context.sha.substring(0, 7)}
            - Deployed by: ${context.actor}
            - URL: https://production.example.com
            `;

            // Post to Slack/Discord/etc or create deployment
            console.log(message);

      - name: Rollback on failure
        if: failure()
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
          SERVER_HOST: ${{ secrets.PRODUCTION_SERVER }}
          SERVER_USER: ${{ secrets.PRODUCTION_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          ssh -i ~/.ssh/deploy_key "$SERVER_USER@$SERVER_HOST" << 'ENDSSH'
            cd /opt/scholarship-system

            # Rollback to previous version
            docker compose down
            git checkout HEAD~1
            docker compose pull
            docker compose up -d
          ENDSSH

          echo "âš ï¸ Rolled back to previous version"
